name: dlna
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  dio: ^5.9.1
  #media_cast_dlna: ^0.2.0
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.2

 # klipt_video_player: ^1.1.4+1
  wakelock_plus: ^1.4.0
  sqflite: ^2.4.2
  tha_player: ^0.5.2
  better_player_plus:
    path: plugins/better_player_plus
  xml: ^6.6.1
  provider: ^6.1.5+1
  video_player: ^2.11.0
  screen_brightness: ^2.1.7
  hardware_button_listener: ^0.0.1
  volume_controller: ^2.0.7
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  multicast_dns: ^0.3.3
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  flutter_foreground_task: ^9.2.0
  youtube_player_flutter: ^9.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
